sudo: false
language: python
python:
  - 2.7
  - 3.6
env:
  - SQLALCHEMY='sqlalchemy>=1.1.0,<1.2.0' DB='all'
  - DJANGO='django>=1.11.0,<1.12.0' DB='all'
matrix:
  fast_finish: true
before_script:
  - psql -c 'create database architect;' -U postgres
  - mysql -e 'create database architect;' -u root
install:
  - travis_retry pip install -r tests/requirements.txt
  - travis_retry pip install coveralls psycopg2 pymysql
  - if [[ $DJANGO ]]; then travis_retry pip install $DJANGO; fi
  - if [[ $SQLALCHEMY ]]; then travis_retry pip install $SQLALCHEMY; fi
script:
  - nosetests --with-coverage --cover-erase --cover-package=architect
after_success:
  - coveralls
